DROP TABLE IF EXISTS pessoa;
DROP TABLE IF EXISTS log_import_csv;

CREATE TABLE pessoa (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  telefone VARCHAR(250) NOT NULL,
  cpf VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  endereco VARCHAR(250) DEFAULT NULL,
  tipo VARCHAR(2) NOT NULL
);

CREATE TABLE log_import_csv (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  file VARCHAR(250) NOT NULL
);